[package]
name = "generator"
version = "0.1.0"
authors = ["Cole Helbling <cole.helbling@determinate.systems>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "generator"
path = "src/main.rs"
doctest = false

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
lazy_static = "1.4.0"
pico-args = { version = "0.4.2", default-features = false, features = ["eq-separator"] }
regex = "1.5.4"
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
serde_json = "1.0.65"
