[package]
name = "generator"
version = "0.1.0"
authors = ["Cole Helbling <cole.helbling@determinate.systems>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
lazy_static = "1.4.0"
regex = { version = "1.5.4" }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.65"
